name: Publish Preview Update

on:
  push:
    branches: 
      - "*"
      - "!main"

jobs:
  publish_preview_update:
    name: Publish Preview Update
    type: update
    params:
      branch: ${{ github.ref_name }}
