name: Publish Preview Update

on:
  push:
    branches: 
      - "*"
      - "!main"

jobs:
  # publish_preview_update:
  #   name: Publish Preview Update
  #   type: update
  #   params:
  #     branch: ${{ github.ref_name }}

  run_tests:
    name: Run Tests
    type: custom
    steps:
      - run: npm test
